import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync, statSync } from 'node:fs';
execFileSync('bash',['scripts/build-site.sh'],{stdio:'inherit'});
const required=['index.html','site.css','site.js','premium.css','app.html','app-v2.css','app.js','app-shell.js','styles.css','growth.css','guide-v2.css','pages.css','pages-core.css','pages-sections.css','pages-responsive.css','pages.js','about.html','tutorial.html','premium.html','founder-review.css','founder-review.js','review-sample.html','review-sample.css','service-legal.css','service-legal.js','site-config.js','support.html','download.html','manifest.webmanifest','sw.js','icon.svg','sample-packet.html','privacy.html','terms.html','stripe-service-not-received.html','freelancer-chargeback-response.html','shopify-chargeback-evidence.html','robots.txt','sitemap.xml','release-v8.txt','.nojekyll'];
for(const file of required) assert.ok(statSync(`public/${file}`).isFile(),`Missing public/${file}`);
for(const file of ['site.js','pages.js','app.js','app-shell.js','founder-review.js','service-legal.js','site-config.js','sw.js']) execFileSync(process.execPath,['--check',`public/${file}`],{stdio:'inherit'});
const manifest=JSON.parse(readFileSync('public/manifest.webmanifest','utf8'));assert.equal(manifest.start_url,'./app.html');
const read=file=>readFileSync(`public/${file}`,'utf8');const home=read('index.html');const app=read('app.html');const siteJs=read('site.js');
assert.match(home,/The dispute arrives/);assert.match(home,/assembly-stage/);assert.match(home,/reason-switch/);assert.match(home,/method-visual/);assert.match(home,/site\.css/);assert.doesNotMatch(home,/premium\.css/);assert.doesNotMatch(home,/id="builder"/);
for(const page of ['about.html','tutorial.html','support.html','download.html']){const html=read(page);assert.match(html,/pages\.css/);assert.match(html,/pages\.js/);assert.match(html,/global-header/);assert.match(html,/href="app\.html/);}
assert.match(read('about.html'),/WHY WE MADE IT/);assert.match(read('about.html'),/An evidence workstation/);assert.match(read('tutorial.html'),/Six deliberate passes/);assert.match(read('tutorial.html'),/id="walkNext"/);assert.match(read('support.html'),/id="feedbackForm"/);assert.match(read('support.html'),/public GitHub issue/i);
const premium=read('premium.html');assert.match(premium,/A second set of eyes/);assert.match(premium,/id="fitForm"/);assert.match(premium,/data-price/);assert.match(premium,/founder-review\.css/);assert.match(premium,/site-config\.js/);assert.match(premium,/founder-review\.js/);assert.match(premium,/No outcome promise/);assert.match(premium,/Payment is requested only after the compatibility check/);assert.match(premium,/\$750–\$5,000/);assert.match(premium,/Stripe Smart Disputes or Shopify automation/);assert.doesNotMatch(premium,/\$150–\$2,500/);
const founderJs=read('founder-review.js');const legalJs=read('service-legal.js');const reviewSample=read('review-sample.html');assert.match(reviewSample,/FICTIONAL EXAMPLE/);assert.match(reviewSample,/NO WIN-RATE CLAIM/);assert.match(reviewSample,/\$1,480/);assert.match(founderJs,/review-sample\.html/);assert.match(founderJs,/applicationsOpen === true/);assert.match(founderJs,/acceptedRoute/);assert.match(founderJs,/validPayment/);assert.match(founderJs,/Service operator:/);assert.match(legalJs,/data-operator-status/);assert.match(legalJs,/Service operator:/);
const config=read('site-config.js');assert.match(config,/servicePriceUsd:\s*69/);assert.match(config,/contactEmail:/);assert.match(config,/businessCountry:/);assert.match(config,/paymentUrl:/);assert.match(config,/businessName:\s*""/);assert.match(config,/contactEmail:\s*""/);assert.match(config,/paymentUrl:\s*""/);assert.match(config,/applicationsOpen:\s*false/);assert.doesNotMatch(config,/sk_live_|pk_live_|AKIA[0-9A-Z]{16}/);
const download=read('download.html');assert.match(download,/Open web app/);assert.match(download,/Try fictional demo/);assert.match(download,/DOWNLOAD \.EXE/);assert.match(download,/DOWNLOAD ARM64 \.DMG/);assert.match(download,/DOWNLOAD \.APPIMAGE/);assert.match(download,/disabled/);assert.match(download,/NOT RELEASED/);
assert.match(siteJs,/tutorial\.html/);assert.match(siteJs,/premium\.html/);assert.match(siteJs,/Optional \$69 founder review/);
assert.match(app,/id="builder"/);assert.match(app,/app-v2\.css/);assert.match(app,/premium\.css/);
const ids=['processor','reason','saleType','deadline','caseId','amount','merchant','transactionDate','description','evidenceList','timelineForm','timelineList','scoreValue','scoreRing','responseDraft','evidenceIndex','finalChecks','loadDemo','regenerate','printPacket','exportCase','importCase','resetCase','toast'];for(const id of ids)assert.match(app,new RegExp(`id="${id}"`),`Missing #${id}`);
for(const file of ['sample-packet.html','stripe-service-not-received.html','freelancer-chargeback-response.html','shopify-chargeback-evidence.html']){const html=read(file);assert.match(html,/guide-v2\.css/);assert.match(html,/premium\.css/);assert.match(html,/pages\.css/);}for(const file of ['privacy.html','terms.html']){const html=read(file);assert.match(html,/service-legal\.css/);assert.match(html,/service-legal\.js/);assert.match(html,/data-operator-status/);assert.match(html,/Founder review/);}
const cssLoader=read('pages.css');for(const file of ['pages-core.css','pages-sections.css','pages-responsive.css'])assert.match(cssLoader,new RegExp(file.replace('.','\\.')));
const sw=read('sw.js');assert.match(sw,/rebuttalkit-v8/);assert.match(sw,/release-v8\.txt/);assert.match(sw,/founder-review\.css/);assert.match(sw,/review-sample\.html/);assert.match(sw,/review-sample\.css/);assert.match(sw,/service-legal\.css/);assert.match(sw,/service-legal\.js/);assert.match(sw,/site-config\.js/);
const sitemap=read('sitemap.xml');for(const page of ['about.html','tutorial.html','premium.html','review-sample.html','support.html','download.html'])assert.match(sitemap,new RegExp(page.replace('.','\\.')));
assert.equal(read('release-v8.txt').trim(),'RebuttalKit Revenue Release v8');
const deployable=required.filter(file=>!file.endsWith('.svg')&&file!=='.nojekyll').map(read).join('\n');assert.doesNotMatch(deployable,/sk_live_|pk_live_|AKIA[0-9A-Z]{16}/);
console.log(JSON.stringify({ok:true,release:'v8',files:required.length,pages:6,offer:'high-value-founder-review'}));
